name: Run Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:16

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install dependencies
        run: npm ci

      - name: Run Vitest Suite
        run: npm test
